name: Build
on: [push, pull_request]
jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - name: Clone Tree
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Dependencies
        run: sudo apt install -y gcc-multilib freeglut3-dev
      - name: Build
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: lindbergh-loader
          path: build/
