name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to upload artifacts and create releases
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image and output
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          outputs: type=local,dest=build

      - name: Archive build output
        run: |
          mkdir -p release
          zip -r release/build-output.zip build/*

      - name: Upload build output as a release asset
        id: upload-release
        uses: actions/upload-release-asset@v2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/build-output.zip
          asset_name: build-output.zip
          asset_content_type: application/zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Build - ${{ github.sha }}
          body: |
            Automated release generated by CI.
            Includes the build output from the Docker build.
          draft: false
          prerelease: false
