name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image and output
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          outputs: type=local,dest=build
